// src/routes/av/+page.svelte
<script lang='ts'>
    import "../../stylesheets/pages/music.scss";
    import "../../stylesheets/pages/about.scss";
    import "../../stylesheets/base/text.scss";
    import "../../stylesheets/index.scss";
    import aloe1 from "../../assets/photos/aloe.webp";
    import aloe2 from "../../assets/photos/aloe2.webp";
    import beaner from "../../assets/photos/bean.webp";
</script>

<div class="box">
<h2>My Music</h2>
<ul class="p language-grid">
    <li class="biglist song-list-header">
        <p class="single_line song-list-content">
            <strong><a href="https://soundcloud.com/uptu/moth?si=a81b92a612cd41c1896451d92a06e160&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing" class="link-underline">Moth</a></strong>
            <br/>
            More of an exercise in sound design than a <em>song</em> per se. I used granular synthesis, vocoding, convolution, and pitch-based sample-and-holding to try to create a library of psychedelic sound effects, but ended up composing it more as a standalone track. If Aphex Twin on DMT sounds like a good idea, give this a listen.
        </p>
    </li>
    <li class="biglist song-list-header">
        <p class="single_line song-list-content">
            <strong><a href="https://soundcloud.com/uptu/opvs/s-nKODx?si=8ca1a917729d45ef924e2c704adebf4b&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing" class="link-underline">Opvs</a></strong>
            <br/>
            I never ended up releasing this halftime DnB track back when I first finished it back in the late 2010s, as it never quite felt 'done' to me. Now it still remains as my most polished-sounding track.
        </p>
    </li>
    <li class="biglist song-list-header">
        <p class="single_line song-list-content">
            <strong><a href="https://soundcloud.com/uptu/psytrance-wip/s-ytFqkzaoKFv?in=uptu/sets/alterplace/s-bJ6UrHN5h9N&si=06c95ba24cb94c2383726d59608824d0&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing" class="link-underline">Psytrance WIP [NAME TBD]</a></strong>
            <br/>
            Just a nice straightforward psytrance track project sitting somewhere around 50% completion. Needs some more glitching to get more in my style, but is has a nice foundation behind it right now.
        </p>
    </li>
</ul>
</div>
<div class="box">
<h2>My Photos</h2>
<ul class="p language-grid">
    <li class="biglist song-list-header">
        <p class="single_line song-list-content">
            <a href="https://drive.google.com/file/d/1ERYbwHB7FZSl1YC-FQRTJi1_whmuHiIn/view?usp=sharing">
                <img class="image" src={aloe1} alt="Aloe Vera" />
            </a>
        </p>
    </li>
    <li class="biglist song-list-header">
        <p class="single_line song-list-content">
            <a href="https://drive.google.com/file/d/1ydlmVn76yfRSCFaMJ3GsM8PO4QARWT96/view?usp=sharing">
                <img class="image" src={aloe2} alt="Aloe Vera" />
            </a>

        </p>
    </li>
    <li class="biglist song-list-header">
        <p class="single_line song-list-content">
            <a href="https://drive.google.com/file/d/1FQ8-cRy2Jj-JrmkMCMygnikRszbq2WfF/view?usp=sharing">
                <img class="image" src={beaner} alt="My Cat" />
            </a>
        </p>
    </li>
</ul>
</div>

// src/pages/AV.tsx
import "../stylesheets/pages/music.scss";
import aloe1 from "../assets/photos/aloe.webp";
import aloe2 from "../assets/photos/aloe2.webp";
import beaner from "../assets/photos/bean.webp";

const AV = () => {
    return(
        <>
            <div className="box">
            <h2>My Music</h2>
            <ul className="p language-grid">
                <li className="biglist song-list-header">
                    <p className="single_line song-list-content">
                        <strong><a href="https://soundcloud.com/uptu/moth?si=a81b92a612cd41c1896451d92a06e160&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing" className="link-underline">Moth</a></strong>
                        <br/>
                        More of an exercise in sound design than a <em>song</em> per se. I used granular synthesis, vocoding, convolution, and pitch-based sample-and-holding to try to create a library of psychedelic sound effects, but ended up composing it more as a standalone track. If Aphex Twin on DMT sounds like a good idea, give this a listen.
                    </p>
                </li>
                <li className="biglist song-list-header">
                    <p className="single_line song-list-content">
                        <strong><a href="https://soundcloud.com/uptu/opvs/s-nKODx?si=8ca1a917729d45ef924e2c704adebf4b&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing" className="link-underline">Opvs</a></strong>
                        <br/>
                        I never ended up releasing this halftime DnB track back when I first finished it back in the late 2010s, as it never quite felt 'done' to me. Now it still remains as my most polished-sounding track.
                    </p>
                </li>
                <li className="biglist song-list-header">
                    <p className="single_line song-list-content">
                        <strong><a href="https://soundcloud.com/uptu/psytrance-wip/s-ytFqkzaoKFv?in=uptu/sets/alterplace/s-bJ6UrHN5h9N&si=06c95ba24cb94c2383726d59608824d0&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing" className="link-underline">Psytrance WIP [NAME TBD]</a></strong>
                        <br/>
                        Just a nice straightforward psytrance track project sitting somewhere around 50% completion. Needs some more glitching to get more in my style, but is has a nice foundation behind it right now.
                    </p>
                </li>
            </ul>
            </div>
            <div className="box">
            <h2>My Photos</h2>
            <ul className="p language-grid">
                <li className="biglist song-list-header">
                    <p className="single_line song-list-content">
                        <a href="https://drive.google.com/file/d/1ERYbwHB7FZSl1YC-FQRTJi1_whmuHiIn/view?usp=sharing">
                            <img className="image" src={aloe1} alt="Aloe Vera" />
                        </a>
                    </p>
                </li>
                <li className="biglist song-list-header">
                    <p className="single_line song-list-content">
                        <a href="https://drive.google.com/file/d/1ydlmVn76yfRSCFaMJ3GsM8PO4QARWT96/view?usp=sharing">
                            <img className="image" src={aloe2} alt="Aloe Vera" />
                        </a>

                    </p>
                </li>
                <li className="biglist song-list-header">
                    <p className="single_line song-list-content">
                        <a href="https://drive.google.com/file/d/1FQ8-cRy2Jj-JrmkMCMygnikRszbq2WfF/view?usp=sharing">
                            <img className="image" src={beaner} alt="My Cat" />
                        </a>
                    </p>
                </li>
            </ul>
            </div>
        </>
    );
}

export default AV;
